name: Test cron input

on:
  workflow_dispatch:
    inputs:
      environment:
        description: 'Environment'
        required: true
        type: choice
        options:
          - pippo
          - peppe
        default: pippo

  schedule:
    - cron: "20 * 24 9 *"

jobs:
  run_tests:
    runs-on: ubuntu-latest

    env:
      ENV: ${{ github.event_name == 'schedule' && 'pippo' || inputs.environment }}
    
    steps:
      - name: Show environment
        run: echo "ENV is '$ENV'"
